import { Character, Enemy } from '../types';

export const LEVELS = [
  // 危险性1级 - 口腔疾病（龋齿、牙龈炎等）
  { id: 'mouth-easy', name: '口腔-初级', difficulty: 1, organId: 'mouth', color: '#FFE0B2', wallColor: '#FFB74D', emoji: '🦷' },
  { id: 'nose-easy', name: '鼻腔-初级', difficulty: 1, organId: 'nose', color: '#E1F5FE', wallColor: '#81D4FA', emoji: '👃' },
  { id: 'skin-easy', name: '皮肤-初级', difficulty: 1, organId: 'skin', color: '#F5F5F5', wallColor: '#E0E0E0', emoji: '🫄' },
  
  // 危险性2级 - 轻度感染疾病
  { id: 'ear-medium', name: '耳朵-中级', difficulty: 2, organId: 'ear', color: '#FFF8E1', wallColor: '#FFECB3', emoji: '👂' },
  { id: 'stomach-medium', name: '胃部-中级', difficulty: 2, organId: 'stomach', color: '#FFF3E0', wallColor: '#FFCC80', emoji: '🤢' },
  { id: 'intestine-medium', name: '肠道-中级', difficulty: 2, organId: 'intestine', color: '#F3E5F5', wallColor: '#CE93D8', emoji: '💩' },
  { id: 'throat-medium', name: '咽喉-中级', difficulty: 2, organId: 'throat', color: '#FFEBEE', wallColor: '#FFCDD2', emoji: '🗣️' },
  
  // 危险性3级 - 需及时治疗的中等疾病
  { id: 'lung-hard', name: '肺部-高级', difficulty: 3, organId: 'lung', color: '#E3F2FD', wallColor: '#90CAF9', emoji: '🫁' },
  { id: 'liver-hard', name: '肝脏-高级', difficulty: 3, organId: 'liver', color: '#FFCDD2', wallColor: '#EF9A9A', emoji: '🫀' },
  { id: 'blood-hard', name: '血管-高级', difficulty: 3, organId: 'blood', color: '#FFEBEE', wallColor: '#EF9A9A', emoji: '🩸' },
  
  // 危险性4级 - 可能危及生命的严重疾病
  { id: 'kidney-expert', name: '肾脏-专家', difficulty: 4, organId: 'kidney', color: '#D1C4E9', wallColor: '#B39DDB', emoji: '🫘' },
  { id: 'heart-expert', name: '心脏-专家', difficulty: 4, organId: 'heart', color: '#EF9A9A', wallColor: '#E57373', emoji: '❤️' },
  { id: 'brain-expert', name: '大脑-专家', difficulty: 4, organId: 'brain', color: '#E0E0E0', wallColor: '#BDBDBD', emoji: '🧠' },
  
  // 危险性5级 - 极易致命的危急疾病
  { id: 'cardio-master', name: '心血管-大师', difficulty: 5, organId: 'cardiovascular', color: '#B71C1C', wallColor: '#D32F2F', emoji: '💔' },
  { id: 'nervous-master', name: '中枢神经-大师', difficulty: 5, organId: 'nervous', color: '#424242', wallColor: '#616161', emoji: '⚡' },
];

export const ORGANS = [
  // 危险性1级
  { id: 'mouth', name: '口腔', color: '#FFE0B2', wallColor: '#FFB74D', dangerLevel: 1 },
  { id: 'nose', name: '鼻腔', color: '#E1F5FE', wallColor: '#81D4FA', dangerLevel: 1 },
  { id: 'skin', name: '皮肤', color: '#F5F5F5', wallColor: '#E0E0E0', dangerLevel: 1 },
  
  // 危险性2级
  { id: 'ear', name: '耳朵', color: '#FFF8E1', wallColor: '#FFECB3', dangerLevel: 2 },
  { id: 'stomach', name: '胃部', color: '#FFF3E0', wallColor: '#FFCC80', dangerLevel: 2 },
  { id: 'intestine', name: '肠道', color: '#F3E5F5', wallColor: '#CE93D8', dangerLevel: 2 },
  { id: 'throat', name: '咽喉', color: '#FFEBEE', wallColor: '#FFCDD2', dangerLevel: 2 },
  
  // 危险性3级
  { id: 'lung', name: '肺部', color: '#E3F2FD', wallColor: '#90CAF9', dangerLevel: 3 },
  { id: 'liver', name: '肝脏', color: '#FFCDD2', wallColor: '#EF9A9A', dangerLevel: 3 },
  { id: 'blood', name: '血管', color: '#FFEBEE', wallColor: '#EF9A9A', dangerLevel: 3 },
  
  // 危险性4级
  { id: 'kidney', name: '肾脏', color: '#D1C4E9', wallColor: '#B39DDB', dangerLevel: 4 },
  { id: 'heart', name: '心脏', color: '#EF9A9A', wallColor: '#E57373', dangerLevel: 4 },
  { id: 'brain', name: '大脑', color: '#E0E0E0', wallColor: '#BDBDBD', dangerLevel: 4 },
  
  // 危险性5级
  { id: 'cardiovascular', name: '心血管', color: '#B71C1C', wallColor: '#D32F2F', dangerLevel: 5 },
  { id: 'nervous', name: '中枢神经', color: '#424242', wallColor: '#616161', dangerLevel: 5 },
];

export const IMMUNE_CELLS: Character[] = [
  {
    id: 'macrophage',
    name: '巨噬细胞',
    type: 'macrophage',
    hp: 6,
    maxHp: 6,
    defense: 2,
    emoji: '🛡️',
    color: '#4A90E2'
  },
  {
    id: 'neutrophil',
    name: '中性粒细胞',
    type: 'neutrophil',
    hp: 5,
    maxHp: 5,
    defense: 1,
    emoji: '⚔️',
    color: '#F5A623'
  },
  {
    id: 'tcell',
    name: 'T淋巴细胞',
    type: 'tcell',
    hp: 4,
    maxHp: 4,
    defense: 1,
    emoji: '🎯',
    color: '#7ED321'
  },
  {
    id: 'bcell',
    name: 'B淋巴细胞',
    type: 'bcell',
    hp: 4,
    maxHp: 4,
    defense: 3,
    emoji: '📡',
    color: '#BD10E0'
  },
  {
    id: 'nkcell',
    name: 'NK细胞',
    type: 'nkcell',
    hp: 5,
    maxHp: 5,
    defense: 2,
    emoji: '💣',
    color: '#D0021B'
  }
];

export const PROBIOTICS: Character[] = [
  {
    id: 'lactobacillus',
    name: '乳杆菌',
    type: 'probiotic',
    probioticType: 'lactobacillus',
    hp: 4,
    maxHp: 4,
    defense: 2,
    emoji: '🥛',
    color: '#68D391'
  },
  {
    id: 'bifidobacterium',
    name: '双歧杆菌',
    type: 'probiotic',
    probioticType: 'bifidobacterium',
    hp: 5,
    maxHp: 5,
    defense: 3,
    emoji: '🍼',
    color: '#9F7AEA'
  },
  {
    id: 'lactobacillus_acidophilus',
    name: '嗜酸乳杆菌',
    type: 'probiotic',
    probioticType: 'lactobacillus_acidophilus',
    hp: 4,
    maxHp: 4,
    defense: 1,
    emoji: '🧀',
    color: '#F6E05E'
  },
  {
    id: 'lactobacillus_rhamnosus',
    name: '鼠李糖乳杆菌',
    type: 'probiotic',
    probioticType: 'lactobacillus_rhamnosus',
    hp: 4,
    maxHp: 4,
    defense: 2,
    emoji: '🥛',
    color: '#4FD1C5'
  },
  {
    id: 'saccharomyces',
    name: '布拉氏酵母菌',
    type: 'probiotic',
    probioticType: 'saccharomyces',
    hp: 3,
    maxHp: 3,
    defense: 1,
    emoji: '🍞',
    color: '#F687B3'
  }
];

export const PATHOGENS: Enemy[] = [
  {
    id: 'e_coli',
    name: '大肠杆菌',
    type: 'bacteria',
    subtype: 'e_coli',
    hp: 3,
    maxHp: 3,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '嗨嗨！我是大肠杆菌，住在肠道里的小家伙~ 虽然我看起来很小，但我的家族可庞大啦！要不要跟我比一比谁能先占领这片领地呢？'
  },
  {
    id: 'staph_epidermidis',
    name: '表皮葡萄球菌',
    type: 'bacteria',
    subtype: 'staph_epidermidis',
    hp: 3,
    maxHp: 3,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '你好呀！我是表皮葡萄球菌，喜欢住在皮肤上开派对~ 我们圆圆的脑袋聚在一起，就像一串串小葡萄，可爱吧？'
  },
  {
    id: 'strep_pneumoniae',
    name: '肺炎链球菌',
    type: 'bacteria',
    subtype: 'strep_pneumoniae',
    hp: 3,
    maxHp: 3,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '嘿嘿，我是肺炎链球菌，住在肺部的好朋友~ 我喜欢手拉手排成一队，像小火车一样前进！你也来加入我们的队伍吧？'
  },
  {
    id: 'candida_albicans',
    name: '白色念珠菌',
    type: 'bacteria',
    subtype: 'candida_albicans',
    hp: 3,
    maxHp: 3,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🍄',
    intro: '大家好！我是白色念珠菌，长得像小蘑菇一样可爱~ 我喜欢在温暖潮湿的地方安家，要不要来我的菌落做客呀？'
  },
  {
    id: 'rhinovirus',
    name: '鼻病毒',
    type: 'virus',
    subtype: 'rhinovirus',
    hp: 2,
    maxHp: 2,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🤧',
    intro: '阿嚏！我是鼻病毒，专门爱让人打喷嚏~ 虽然我很小，但我的速度超快，想抓住我可不容易哦！'
  },
  {
    id: 'adenovirus',
    name: '腺病毒',
    type: 'virus',
    subtype: 'adenovirus',
    hp: 2,
    maxHp: 2,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '你好呀！我是腺病毒，有着超级可爱的小脸蛋~ 我喜欢到处冒险，你能跟上我的节奏吗？'
  },
  {
    id: 'haemophilus',
    name: '流感嗜血杆菌',
    type: 'bacteria',
    subtype: 'haemophilus',
    hp: 3,
    maxHp: 3,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '我是流感嗜血杆菌，虽然名字有点复杂，但我其实是很好相处的~ 喜欢和大家一起玩耍，来交个朋友吧！'
  },
  {
    id: 'moraxella',
    name: '卡他莫拉菌',
    type: 'bacteria',
    subtype: 'moraxella',
    hp: 3,
    maxHp: 3,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '哈喽！我是卡他莫拉菌，喜欢住在呼吸系统里~ 我的脾气可好了，就是有点调皮，想不想跟我玩躲猫猫？'
  },
  {
    id: 'parainfluenza',
    name: '副流感病毒',
    type: 'virus',
    subtype: 'parainfluenza',
    hp: 2,
    maxHp: 2,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '我是副流感病毒，流感病毒的小表弟~ 我虽然个子小，但也会让人咳嗽哦！要不要来一场精彩的较量？'
  },
  {
    id: 'enterococcus',
    name: '肠球菌',
    type: 'bacteria',
    subtype: 'enterococcus',
    hp: 3,
    maxHp: 3,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '嗨！我是肠球菌，肠道里的老住户啦~ 我很强壮，不怕环境变化，看看我们谁更厉害！'
  },
  {
    id: 'proteus',
    name: '变形杆菌',
    type: 'bacteria',
    subtype: 'proteus',
    hp: 3,
    maxHp: 3,
    attack: 2,
    dangerLevel: 1,
    counterAttackTime: 20,
    emoji: '🦠',
    intro: '我是变形杆菌，就像变形金刚一样会变化形状~ 你永远猜不到我下一个动作是什么，哈哈哈！'
  },
  {
    id: 'influenza',
    name: '流感病毒',
    type: 'virus',
    subtype: 'influenza',
    hp: 3,
    maxHp: 3,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🤧',
    intro: '呼呼！我是流感病毒，每年都要出来搞点事情~ 我会变变变，让你怎么都防不住我！来吧，和我比一比谁的变化多！'
  },
  {
    id: 'salmonella',
    name: '沙门氏菌',
    type: 'bacteria',
    subtype: 'salmonella',
    hp: 4,
    maxHp: 4,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '你好！我是沙门氏菌，喜欢藏在食物里搞恶作剧~ 我有尾巴会游泳，速度快得像闪电，你追不上我吧！'
  },
  {
    id: 'roundworm',
    name: '蛔虫',
    type: 'parasite',
    subtype: 'roundworm',
    hp: 4,
    maxHp: 4,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🐛',
    intro: '嗷呜！我是蛔虫，一条长长的虫子~ 我喜欢在肠道里扭来扭去，看我跳舞吧！想抓住我，可不容易哦~'
  },
  {
    id: 'h_pylori',
    name: '幽门螺杆菌',
    type: 'bacteria',
    subtype: 'h_pylori',
    hp: 4,
    maxHp: 4,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '嗨嗨！我是幽门螺杆菌，住在胃里的勇士~ 胃酸都伤不到我，我很厉害吧？来挑战我看看！'
  },
  {
    id: 'pertussis',
    name: '百日咳杆菌',
    type: 'bacteria',
    subtype: 'pertussis',
    hp: 4,
    maxHp: 4,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '咳咳咳！我是百日咳杆菌，专门让人咳个不停~ 我的声音可大啦，比我还吵的对手可不多见！'
  },
  {
    id: 'tetanus',
    name: '破伤风杆菌',
    type: 'bacteria',
    subtype: 'tetanus',
    hp: 4,
    maxHp: 4,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '我是破伤风杆菌，喜欢在泥土里睡觉~ 我会让人肌肉紧张绷绷的，就像我一样有力量！'
  },
  {
    id: 'pseudomonas',
    name: '铜绿假单胞菌',
    type: 'bacteria',
    subtype: 'pseudomonas',
    hp: 4,
    maxHp: 4,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '嘿！我是铜绿假单胞菌，穿着绿色外衣的小家伙~ 我生命力超强，什么环境都能生存，跟我比比耐力吧！'
  },
  {
    id: 'hookworm',
    name: '钩虫',
    type: 'parasite',
    subtype: 'hookworm',
    hp: 4,
    maxHp: 4,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🐛',
    intro: '我是钩虫，嘴上有小钩子的小坏蛋~ 我喜欢挂在肠壁上，看我这个绝技，厉害吧？来试试能不能把我甩掉！'
  },
  {
    id: 'measles',
    name: '麻疹病毒',
    type: 'virus',
    subtype: 'measles',
    hp: 3,
    maxHp: 3,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '嘻嘻！我是麻疹病毒，喜欢在皮肤上画画~ 我会留下红色的小斑点，就像我的签名一样！'
  },
  {
    id: 'varicella',
    name: '水痘-带状疱疹病毒',
    type: 'virus',
    subtype: 'varicella',
    hp: 3,
    maxHp: 3,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '我是水痘-带状疱疹病毒，会让人身上长小水泡~ 我喜欢玩躲猫猫，有时候还会藏起来很久呢！'
  },
  {
    id: 'rsv',
    name: '呼吸道合胞病毒',
    type: 'virus',
    subtype: 'rsv',
    hp: 3,
    maxHp: 3,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '你好！我是呼吸道合胞病毒，呼吸道里的常客~ 我喜欢和小细胞们融合在一起，变成更大的家族！'
  },
  {
    id: 'mumps',
    name: '腮腺炎病毒',
    type: 'virus',
    subtype: 'mumps',
    hp: 3,
    maxHp: 3,
    attack: 3,
    dangerLevel: 2,
    counterAttackTime: 15,
    emoji: '🦠',
    intro: '我是腮腺炎病毒，会让腮帮子鼓起来~ 看起来像仓鼠一样可爱，对吧？要不要跟我比比谁的腮帮子大？'
  },

  {
    id: 'golden_staph',
    name: '金黄色葡萄球菌',
    type: 'bacteria',
    subtype: 'golden_staph',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '哇哦！我是金黄色葡萄球菌，穿着闪亮金色战衣的战士~ 我可厉害了，很多药物都对付不了我，敢不敢来试试？'
  },
  {
    id: 'shigella',
    name: '痢疾杆菌',
    type: 'bacteria',
    subtype: 'shigella',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '嘿嘿！我是痢疾杆菌，肠道里的小捣蛋~ 我会让肚子变得很不舒服，看你能坚持多久！'
  },
  {
    id: 'typhoid',
    name: '伤寒杆菌',
    type: 'bacteria',
    subtype: 'typhoid',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '我是伤寒杆菌，历史悠久的对手~ 从古代开始我就让人闻风丧胆，你的实力能打败我吗？'
  },
  {
    id: 'cholera',
    name: '霍乱弧菌',
    type: 'bacteria',
    subtype: 'cholera',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '嗨！我是霍乱弧菌，喜欢在水里游泳的小家伙~ 我长得像逗号，游得可快了，追不上我吧！'
  },

  {
    id: 'filarial_worm',
    name: '丝虫',
    type: 'parasite',
    subtype: 'filarial_worm',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🐛',
    intro: '我是丝虫，细长又优雅的舞者~ 我喜欢在淋巴系统里跳舞，我的舞姿很美，你不想看看吗？'
  },
  {
    id: 'chlamydia',
    name: '衣原体',
    type: 'bacteria',
    subtype: 'chlamydia',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '你好！我是衣原体，像小细菌又像小病毒~ 我很小很小，需要用特殊方法才能看到我，神奇吧？'
  },
  {
    id: 'leptospira_mild',
    name: '钩端螺旋体',
    type: 'bacteria',
    subtype: 'leptospira_mild',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '我是钩端螺旋体，卷卷的像个小弹簧~ 我喜欢在脏水里玩耍，你敢不敢跟我来个比赛？'
  },
  {
    id: 'candida_invasive',
    name: '侵袭性念珠菌',
    type: 'bacteria',
    subtype: 'candida_invasive',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🍄',
    intro: '我是侵袭性念珠菌，念珠菌里的凶猛派~ 我不仅会待在表面，还会往深处钻，看我的厉害！'
  },
  {
    id: 'hepatitis',
    name: '肝炎病毒',
    type: 'virus',
    subtype: 'hepatitis',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '我是肝炎病毒，喜欢住在肝脏里~ 我会让肝脏很辛苦，但我不坏，只是想找个地方住而已~'
  },
  {
    id: 'influenza_b',
    name: '乙型流感病毒',
    type: 'virus',
    subtype: 'influenza_b',
    hp: 4,
    maxHp: 4,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🤧',
    intro: '呼呼！我是乙型流感病毒，甲流的好兄弟~ 我们俩常常一起出来捣乱，你能同时打败我们两个吗？'
  },
  {
    id: 'polio',
    name: '脊髓灰质炎病毒',
    type: 'virus',
    subtype: 'polio',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '我是脊髓灰质炎病毒，专门攻击神经系统~ 我会让肌肉不听使唤，但如果你有疫苗，我就会跑掉！'
  },
  {
    id: 'klebsiella',
    name: '肺炎克雷伯菌',
    type: 'bacteria',
    subtype: 'klebsiella',
    hp: 5,
    maxHp: 5,
    attack: 4,
    dangerLevel: 3,
    counterAttackTime: 10,
    emoji: '🦠',
    intro: '你好！我是肺炎克雷伯菌，穿厚厚铠甲的战士~ 我有特殊的保护层，很多武器都打不穿我哦！'
  },
  {
    id: 'marburg',
    name: '马尔堡病毒',
    type: 'virus',
    subtype: 'marburg',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '☣️',
    intro: '嘿嘿嘿！我是马尔堡病毒，让人闻风丧胆的存在~ 我的力量超强，不过我相信你的智慧更强大，来较量吧！'
  },
  {
    id: 'tapeworm',
    name: '绦虫',
    type: 'parasite',
    subtype: 'tapeworm',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🐛',
    intro: '我是绦虫，世界上最长的寄生虫之一~ 我有一节一节的身体，像火车一样长，你想数数我有多少节吗？'
  },
  {
    id: 'smallpox',
    name: '天花病毒',
    type: 'virus',
    subtype: 'smallpox',
    hp: 7,
    maxHp: 7,
    attack: 6,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '☣️',
    intro: '我是天花病毒，曾经统治世界的王者~ 虽然疫苗已经把我打败了，但我还是想和你比一比！'
  },
  {
    id: 'rabies',
    name: '狂犬病毒',
    type: 'virus',
    subtype: 'rabies',
    hp: 8,
    maxHp: 8,
    attack: 6,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '☣️',
    intro: '吼吼！我是狂犬病毒，最疯狂的家伙~ 我会让人变得很激动，像我一样充满活力！小心被我的热情传染哦！'
  },
  {
    id: 'dengue',
    name: '登革热病毒',
    type: 'virus',
    subtype: 'dengue',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🦠',
    intro: '你好！我是登革热病毒，喜欢跟着蚊子到处旅行~ 我的身体会发热发烧，但我不想伤害谁，只是想找朋友！'
  },
  {
    id: 'west_nile',
    name: '西尼罗河病毒',
    type: 'virus',
    subtype: 'west_nile',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🦠',
    intro: '我是西尼罗河病毒，来自远方的小客人~ 我喜欢跟着鸟类旅行，见识过很多地方，想听听我的故事吗？'
  },
  {
    id: 'yellow_fever',
    name: '黄热病病毒',
    type: 'virus',
    subtype: 'yellow_fever',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🦠',
    intro: '嗨！我是黄热病病毒，穿黄色衣服的小家伙~ 我会让人发烧和变黄，就像我的衣服一样！'
  },
  {
    id: 'malaria',
    name: '疟原虫',
    type: 'parasite',
    subtype: 'malaria',
    hp: 8,
    maxHp: 8,
    attack: 6,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🦟',
    intro: '我是疟原虫，让身体发热打摆子的小家伙~ 我喜欢躲在红细胞里玩捉迷藏，你能找到我吗？'
  },
  {
    id: 'trypanosome',
    name: '锥虫',
    type: 'parasite',
    subtype: 'trypanosome',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🐛',
    intro: '我是锥虫，长着小尾巴的游泳健将~ 我喜欢在血液里游来游去，看我游得有多快！'
  },

  {
    id: 'legionella',
    name: '军团菌',
    type: 'bacteria',
    subtype: 'legionella',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🦠',
    intro: '我是军团菌，像军团一样强大的战士~ 我喜欢在空调系统里安家，凉爽又舒适，你也想加入我的军团吗？'
  },
  {
    id: 'sars',
    name: 'SARS病毒',
    type: 'virus',
    subtype: 'sars',
    hp: 8,
    maxHp: 8,
    attack: 6,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '☣️',
    intro: '我是SARS病毒，曾经引起全世界关注的家伙~ 我戴着皇冠，像病毒界的国王，但我相信你才是真正的主宰！'
  },
  {
    id: 'mers',
    name: 'MERS病毒',
    type: 'virus',
    subtype: 'mers',
    hp: 8,
    maxHp: 8,
    attack: 6,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '☣️',
    intro: '我是MERS病毒，SARS的兄弟~ 我们俩长得很像，但性格不太一样，你能分清我们吗？'
  },
  {
    id: 'zika_virus',
    name: '寨卡病毒',
    type: 'virus',
    subtype: 'zika_virus',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🦠',
    intro: '你好！我是寨卡病毒，来自热带的小客人~ 我喜欢跟着蚊子旅行，见过很多美丽的风景！'
  },
  {
    id: 'chikungunya',
    name: '基孔肯雅病毒',
    type: 'virus',
    subtype: 'chikungunya',
    hp: 7,
    maxHp: 7,
    attack: 5,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🦠',
    intro: '我是基孔肯雅病毒，名字有点复杂但我很好记~ 我会让关节很疼，但我不是故意的，只是想让你记住我！'
  },
  {
    id: 'leishmania',
    name: '利什曼原虫',
    type: 'parasite',
    subtype: 'leishmania',
    hp: 8,
    maxHp: 8,
    attack: 6,
    dangerLevel: 4,
    counterAttackTime: 5,
    emoji: '🐛',
    intro: '我是利什曼原虫，皮肤上的小画家~ 我会留下特殊的印记，就像我的名片一样！'
  },
  {
    id: 'hiv',
    name: 'HIV病毒',
    type: 'virus',
    subtype: 'hiv',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '☣️',
    intro: '嘿嘿，我是HIV病毒，免疫系统最狡猾的对手~ 我会悄悄地偷袭免疫细胞，让你不知不觉就输了！但我知道你比我更聪明！'
  },
  {
    id: 'ebola',
    name: '埃博拉病毒',
    type: 'virus',
    subtype: 'ebola',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '☣️',
    intro: '吼吼！我是埃博拉病毒，最可怕的存在之一~ 我的速度超快，破坏力超强，但你别怕，我相信你有办法打败我！'
  },
  {
    id: 'anthrax_bacillus',
    name: '炭疽杆菌',
    type: 'bacteria',
    subtype: 'anthrax',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '🦠',
    intro: '我是炭疽杆菌，有着坚硬外壳的战士~ 我能形成孢子，在恶劣环境下也能存活，生命超顽强！'
  },
  {
    id: 'tuberculosis',
    name: '结核杆菌',
    type: 'bacteria',
    subtype: 'tuberculosis',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '🦠',
    intro: '你好！我是结核杆菌，会让人咳嗽很久的老对手~ 我很强壮，不怕药物，但我知道你有办法对付我！'
  },
  {
    id: 'mrsa',
    name: '耐甲氧西林金黄色葡萄球菌',
    type: 'bacteria',
    subtype: 'mrsa',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '🦠',
    intro: '嘿嘿！我是MRSA，超级细菌里的强者~ 很多药物都对付不了我，但我相信你的智慧更强大！'
  },
  {
    id: 'cre',
    name: '耐碳青霉烯肠杆菌',
    type: 'bacteria',
    subtype: 'cre',
    hp: 10,
    maxHp: 10,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '🦠',
    intro: '我是CRE，最强的超级细菌之一~ 几乎所有药物对我都没用，但我相信你会找到办法！'
  },

  {
    id: 'lassa_fever',
    name: '拉沙热病毒',
    type: 'virus',
    subtype: 'lassa_fever',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '☣️',
    intro: '我是拉沙热病毒，来自非洲的危险访客~ 我会让身体很不舒服，但我不想伤害谁，只是想和你玩个游戏！'
  },
  {
    id: 'nipah_virus',
    name: '尼帕病毒',
    type: 'virus',
    subtype: 'nipah_virus',
    hp: 10,
    maxHp: 10,
    attack: 8,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '☣️',
    intro: '吼吼！我是尼帕病毒，最危险的存在之一~ 我来自蝙蝠朋友，虽然我很强大，但我相信你会更强大！'
  },
  {
    id: 'hantavirus',
    name: '汉坦病毒',
    type: 'virus',
    subtype: 'hantavirus',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '☣️',
    intro: '我是汉坦病毒，跟着老鼠到处旅行的小家伙~ 我会让肺部受伤，但我不是故意的，只是想找个家！'
  },
  {
    id: 'schistosoma',
    name: '血吸虫',
    type: 'parasite',
    subtype: 'schistosoma',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '🐛',
    intro: '我是血吸虫，喜欢在血液里游泳~ 我长得细长扁平，游起来可漂亮了，你想看看我的游泳技术吗？'
  },
  {
    id: 'cysticercosis',
    name: '囊尾蚴',
    type: 'parasite',
    subtype: 'cysticercosis',
    hp: 10,
    maxHp: 10,
    attack: 8,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '🐛',
    intro: '我是囊尾蚴，绦虫的宝宝~ 我长得圆圆的，像个小水泡，躲在身体深处玩捉迷藏，你能找到我吗？'
  },
  {
    id: 'trichinella',
    name: '旋毛虫',
    type: 'parasite',
    subtype: 'trichinella',
    hp: 9,
    maxHp: 9,
    attack: 7,
    dangerLevel: 5,
    counterAttackTime: 3,
    emoji: '🐛',
    intro: '我是旋毛虫，喜欢在肌肉里打滚的小家伙~ 我会让人很疼，但我不想伤害谁，只是想找个舒服的地方！'
  }
];
